### ISSUE TITLE
Bug with components with element siblings in hydrate mode

### ISSUE THREAD

**Issue by gbj** [gbj/leptos#109]
This came up in Primeagen's stream but I couldn't reproduce; I think it may have been because it was in hydrate mode. 

Something like 

view! { cx,
  <div><ComponentA/><div><ComponentB/></div></div>
}

**Comment by benwis** [comment]
I was able to reproduce a similar bug [here](https://github.com/benwis/leptos/tree/render-bug).

Check out the todo-sqlite-axum example, and the `<TodoApp/>` component in `routes/todos.rs`.

This component renders <Todos/> and the <h1> twice, but if I move Title and Meta into the <header> tag, or wrap `<Title/>`, `<Meta/>`, and `<Routes/>` in a div, it only renders once. It also renders twice if I put Title and Meta just inside the top level div.

**Comment by gbj** [comment]
Weirdly I wasn't actually able to replicate the rendering issue I had. But I did fix at least one other issue with hydration and components neighboring things. Let me know if it makes a difference.

**Comment by benwis** [comment]
I am no longer able to reproduce either, so you must have fixed it. Nice!
