### ISSUE TITLE
Improve API for cyclical element-effect references

### ISSUE THREAD

**Issue by LLBlumire** [gbj/leptos#118]
For example, say you had a page with two buttons, each one when clicked should disable the other button.

In other web frontend UI frameworks, you would do something to this effect

```rust
let b1 = element_ref();
let b2 = element_ref();

let e1 = |_| b2.disable();
let e2 = |_| b1.disable();
```
```html
<button ref=b1 onclick=e1>Click me!</button>
<button ref=b2 onclick=e2>Xor me!</button>
```

This pattern is not currently possible in leptos, as instead of creating a reference with interior mutability that can be set and then used later in the lifecycle of a component, the `_ref` property simply assigns to an uninitialised variable a reference to the element. This is fine, as long as you do not need this kind of cyclical construction.

**Comment by gbj** [comment]
See #120 

The `NodeRef` type is backed by an untracked signal internally, which makes it `Copy`. Thanks for talking through the API with me! I think this should be pretty good.
