### ISSUE TITLE
Extra requests are sent when navigating away from the page

### ISSUE THREAD

**Issue by bryan824** [gbj/leptos#123]
In hackernews example, when navigating away from the story page and user page, it sends extra requests. Since the URL has changed, `params().get("id")` gets nothing, causing a 404 request.

```rust
let story = create_resource(
    cx,
    move || params().get("id").cloned().unwrap_or_default(),
    move |id| async move { api::fetch_api::<api::Story>(&api::story(&format!("item/{id}"))).await },
);
```

**Comment by gbj** [comment]
Thanks I've fixed these just by filtering on whether those IDs are empty before sending the request. Appreciate it.
