### ISSUE TITLE
Axum and Actix Integrations Do Not Properly Handle Windows Directory Style

### ISSUE THREAD

**Issue by Indrazar** [gbj/leptos#143]
When building examples `todo-app-sqlite` and `todo-app-sqlite-axum` on Windows the buttons generate with function names which are different than the integration handlers expect:
(actix) [handle_server_fns()](https://github.com/gbj/leptos/blob/8d671866a3402f2e65e33ef73348e6750bcb1043/integrations/actix/src/lib.rs#L40) 
(axum) [handle_server_fns()](https://github.com/gbj/leptos/blob/8d671866a3402f2e65e33ef73348e6750bcb1043/integrations/axum/src/lib.rs#L42)

Actix:
When placing this line on line 50 in the integrations lib.rs:
```rust
println!("landed at handle_server_fns, looking for {path}");
```
The following output is generated:
```text
landed at handle_server_fns, looking for examples/todo-app-sqlite/src/todo.rs-add_todo
landed at handle_server_fns, looking for examples/todo-app-sqlite/src/todo.rs-get_todos
```

Axum:
When placing this line on line 50 after / is removed in the integrations lib.rs:
```rust
println!("landed at handle_server_fns, looking for {fn_name}");
```
The following output is generated:
```text
2022-12-01T02:33:01.373Z DEBUG [hyper::proto::h1::io] parsed 17 headers
2022-12-01T02:33:01.373Z DEBUG [hyper::proto::h1::conn] incoming body is content-length (4 bytes)
2022-12-01T02:33:01.374Z DEBUG [hyper::proto::h1::conn] incoming body completed
landed at handle_server_fns, looking for examplestodo-app-sqlite-axumsrctodo.rs-delete_todo
Body: b"id=4"
2022-12-01T02:33:01.377Z DEBUG [hyper::proto::h1::io] flushed 132 bytes
2022-12-01T02:33:01.380Z DEBUG [hyper::proto::h1::io] parsed 17 headers
2022-12-01T02:33:01.380Z DEBUG [hyper::proto::h1::conn] incoming body is empty
landed at handle_server_fns, looking for examplestodo-app-sqlite-axumsrctodo.rs-get_todos
Body: b""
```
Relevant lines only for clarity:
```text
landed at handle_server_fns, looking for examplestodo-app-sqlite-axumsrctodo.rs-delete_todo
landed at handle_server_fns, looking for examplestodo-app-sqlite-axumsrctodo.rs-get_todos
```

**Comment by gbj** [comment]
Merged your PR fixing it. Thanks so much!
