### ISSUE TITLE
Unable to install router and meta on stable

### ISSUE THREAD

**Issue by peteringram0** [gbj/leptos#151]
The dependencies of;
dont seem to work when using stable leptos version.

````.toml
leptos_router = { version = "0.0.5", features = ["stable"] }
leptos_meta = { version = "0.0.4", features = ["stable"] }
````

**Comment by gbj** [comment]
You are correct! Adding the stable feature to them is on my list, but not done yet. I'll leave this open until it's done.

**Comment by gbj** [comment]
The latest versions of the `leptos_router` and `leptos_meta` packages should now have `stable` flags you can enable, just like the main package. This required some changes so please let me know if anything seems broken! And thanks for pointing it out.
