### ISSUE TITLE
Compilation Speed for relatively large application

### ISSUE THREAD

**Issue by kunjee17** [gbj/leptos#155]
Hi, I heard you on podcast rustocean. And I was fascinated that you took the signal route.  I really like what signal js doing.

Again I really like to use Rust on server and also on client. Had kind of good run with Yew. But until things go south at the compile time. 

We are having relatively large application and compilation time take practically life time. And obviously there is no HMR. This makes designing so hard. You change one CSS and it will take too much time to reflect. 

What is story with leptos? Means how it is in terms of compilation time? Specially when you are have too many files and relatively large application.

**Comment by gbj** [comment]
There isn't hot-module reloading, but there are dev servers that include live-reloading, including Trunk and our own `cargo-leptos`. Your CSS should update more or less immediately, assuming it's in a CSS file and not in a `.rs` file. Any changes to Rust files will require recompilation, and Rust being a relatively slow-to-compile compiled language, this is significantly slower than JavaScript.

I wouldn't expect any meaningful difference in compilation times between Leptos, Yew, and any other Rust framework for a project of similar complexity — this is mostly outside our control.
