### ISSUE TITLE
Add helper functions/macros for JS closure ergonomics

### ISSUE THREAD

**Issue by Innominus** [gbj/leptos#164]
As discussed with GBJ previously, creating closures and wrapping them up for a JS event handler is quite tedious, so I'm bringing this up in case we would like to add a helper to Leptos. 
Currently, creating a closure for event handlers looks like this:
`
let on_close_cb = Closure::new(Box::new(on_close) as Box<dyn FnMut(Event)>).into_js_value();
` 
Unsure on an API, but a macro or function that wraps up your closure into this nice box would be handy.

**Comment by gbj** [comment]
I’m going to close this for now. Feel free to open another issue if we need more specific helpers not included in Gloo.
