### ISSUE TITLE
cargo-leptos can't find sass binaries

### ISSUE THREAD

**Issue by msmaiaa** [gbj/leptos#184]
I am using Windows 10 with rust nightly and this problem occurs with a fresh project created using "cargo leptos new --git https://github.com/leptos-rs/start"

![error](https://i.imgur.com/YqqYLrr.png)

I think it happens because the extracted content actually has a "dart-sass" folder instead of the sass binaries:
![folder](https://i.imgur.com/IwDCFcC.png)
The build process runs just fine if i move the files from the "dart-sass" folder to the sass folder
![folder2](https://i.imgur.com/T53taLz.png)

**Comment by gbj** [comment]
Could you open an issue on the [cargo-leptos repo](https://github.com/akesson/cargo-leptos) please?

**Comment by msmaiaa** [comment]
Sure!
