### ISSUE TITLE
Set up some kind of CI pipeline

### ISSUE THREAD

**Issue by gbj** [gbj/leptos#19]
I'm really ignorant about CI setups so I'd love some help with this.

Various parts of the repo use ordinary `cargo test`. I also have wasm-bindgen tests set up for some of the examples.

**Comment by akesson** [comment]
I'm normally on GitLab, but I'll have a look tomorrow. I propose to set it up so that all valid combinations of flags are built and tested using [cargo-all-features](https://crates.io/crates/cargo-all-features). 

There's no workspace. Is it ok to add one?

**Comment by gbj** [comment]
The short version: `csr`, `hydrate`, and `ssr` are basically mutually exclusive. One of them needs to be enabled for some of the doctests to run — `ssr` is probably best for these.

**Comment by gbj** [comment]
Thanks to the work in PRs #19, #44, and #46 we now have a GitHub Action that runs `cargo make build` and `cargo make test` on every PR. That's enough for me to close this for now. Thanks for all the help.
