### ISSUE TITLE
Release mode is broken in the latest master version

### ISSUE THREAD

**Issue by Innominus** [gbj/leptos#199]
The first alpha revision works fine with everything rendering (2e68f746dcbf7d9f96397a0c6b8f5107bbf4c5e2), but the latest version on master when you build in release mode seems to not be functioning correctly. It's similar to when you set your release mode build to have 'strip = true'. All of the files will load correctly in the browser but you will be greeted with a white screen and no console errors.

Build tool is Trunk 0.16.0 on Rustc Nightly

**Comment by gbj** [comment]
@jquesada2016 could you take a look when you're back from traveling?

I can reproduce — for example a simple `cd examples/counter && trunk serve --release --open` yields a blank screen. I added a few diagnostic logs and it looks like it
- loads and runs Wasm
- runs the `mount_to_body`
- gets to `<SimpleCounter/>` but does not seem to create its children

I wonder if this may be related to the `prepare_to_move` changes, as I think these came after the alpha but before current `main` branch?
