### ISSUE TITLE
svg vs SVG in hydration

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gbj/leptos#212]
As far as I can tell, (I'm on commit d5f8d3a9b712232a573efa2a65ba856a838ced0f), any svg tag causes a hydration mismatch so `<svg></svg>` should be enough to cause the issue.

This is what I see in the console, which points to `svg` vs `SVG`

```
_wasm.js:406 panicked at 'assertion failed: `(left == right)`
  left: `"svg"`,
 right: `"SVG"`: SSR and CSR elements have the same `TopoId` but different node kinds. This is either a discrepancy between SSR and CSR rendering
                    logic, which is considered a bug, or it can also be a leptos hydration issue.', /Users/chris/.cargo/git/checkouts/leptos-852582868f14a87e/d5f8d3a/leptos_dom/src/html/svg.rs:169:1
```

**Comment by gbj** [comment]
Thanks... I love living in a world where `document.createElement("svg").nodeName` is `"SVG"` and `document.createElementNS("http://www.w3.org/2000/svg", "svg")` is `"svg"` Anyway, fixed.
