### ISSUE TITLE
Server Function URLs are hard to debug

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gbj/leptos#225]
When using server functions, there is no way to see the keys in the [`REGISTERED_SERVER_FUNCTIONS` static](https://github.com/gbj/leptos/blob/a2943c464985b2d3baa9d044e38e57ca3a381a52/leptos_server/src/lib.rs#LL103C16-L103C43), and there appears to be no logging on the server around server functions (I'm using the axum integration). 

This makes it difficult to debug when setting up for the first time as the main source of information is the server's response to a misconfigured server function:

```
Could not find a server function at that route.
```

The error indicates that I am hitting the right server-side handler, but apparently the key is wrong as the server function is not found.

It would help to either have some additional logging, or error messaging when a server function misses on the server in development, or additional documentation concerning how the urls are expected to be matched.

**Comment by gbj** [comment]
Thanks — I'll work on adding some things to make this easier!

In the specific case: did you call [`ServerFn::register`](https://docs.rs/leptos_server/0.0.22/leptos_server/trait.ServerFn.html#method.register) for this server function type somwhere in `main.rs`?

i.e.,
```rust
// when you're defining the function, it gets this type name
#[server(MyServerFunction)]
pub async fn my_server_function( ...

// somewhere in `main.rs`
MyServerFunction::register();
```

I just checked and saw that this is included in the examples but missing from the docs, which is a huge fail on my part... I'll make sure to make that clearer.

**Comment by ChristopherBiscardi** [comment]
Needing to register in main was exactly it for me! thank you!

**Comment by gbj** [comment]
Okay, great. Actually adding this information to the error message would probably be really helpful, so I'm going to reopen this just so I don't forget to do it!
```
Could not find a server function at that route. Make sure you are calling MyServerFn::register() somewhere in your main.rs.
```
