### ISSUE TITLE
Bug: append_nodes Failed

### ISSUE THREAD

**Issue by fundon** [gbj/leptos#23]
<img width="827" alt="Screen Shot 2022-10-18 at 3 49 03 PM" src="https://user-images.githubusercontent.com/27926/196369748-a8e8d3af-9991-43c9-a4ca-6942596746b4.png">

## Reproduction

1. run examples/todomvc-ssr/todomvc-ssr-server
2. build examples/todomvc-ssr/todomvc-ssr-client
3. open demo site
4. click `Completed`
5. then click `Active`

<img width="1043" alt="Screen Shot 2022-10-18 at 3 54 35 PM" src="https://user-images.githubusercontent.com/27926/196370534-dc89e3b2-45eb-4eef-bebe-50afb673d83a.png">

**Comment by gbj** [comment]
Thanks! I was able to reproduce it. I'll take a look later today.

**Comment by gbj** [comment]
I believe I've fixed this one. The fix was deceptively easy, but seems to have fixed this particular issue and I haven't seen any other hydration issues pop up, so maybe it was just straightforward.

Anyone feel free to file another issue if it recurs.
