### ISSUE TITLE
Twind or tailwind support

### ISSUE THREAD

**Issue by algoflows** [gbj/leptos#244]
Feature request

Ability to use tailwind css to style components

**Comment by akesson** [comment]
Have a look at https://github.com/gbj/leptos/discussions/125#discussioncomment-4245279

There's a ticket in cargo-leptos already: https://github.com/akesson/cargo-leptos/issues/18

Feel free to contribute with a PR 😄

**Comment by algoflows** [comment]
@akesson I only just started looking at tutorials on rust programming, pretty sure I am a little ways off contributing to a rust built hyper tuned reactivity framework 😅

**Comment by akesson** [comment]
There is certainly a learning curve, but once you pass it you'll never regret spending that time. I'm super happy to use Rust myself. And once you feel ready for contributing: the Leptos community (and most Rust communities) is a great one to help you get your first contributions ready. But in any case, join the Discord where you can ask any questions you'd like: https://discord.gg/YdRAhS7eQB

**Comment by gbj** [comment]
Just chiming in to add: also, check out the [`tailwind` example](https://github.com/gbj/leptos/tree/main/examples/tailwind).

I'm going to close this one, as this is already possible and I've seen examples of folks using it in their apps!
