### ISSUE TITLE
Getting Cargo doc to compile

### ISSUE THREAD

**Issue by martinfrances107** [gbj/leptos#253]
Today when I run 'cargo doc' I see a few trivial bugs which prevent me running the doc locally.

I think lots of micro PR are easier to review ... all linked to a common issue.

I am just going to work on this is the background...

**Comment by gbj** [comment]
Thanks for these, I'll just review and merge them as they come. I have not gone through and really done the docs for the new `leptos_dom` yet.

**Comment by gbj** [comment]
I'll close this issue just to make it easier for myself to track things, but I've appreciated your PRs and will keep merging anything that passes CI and is clearing warnings. Thanks so much for doing this.

**Comment by martinfrances107** [comment]
Ah no problem, I love the projects approach to the problem... ( I am coming here from Yew.rs )
