### ISSUE TITLE
Implement isomorphic "fetch" function

### ISSUE THREAD

**Issue by janschiefer** [gbj/leptos#258]
A HTTP "fetch" function should be implemented, that provides a single and easy to use interface regardless if you are calling it from client (wasm) or server side (native).

Manipulation of headers (content type, authentication...) and request body should be possible without too much hassle.

**Comment by gbj** [comment]
You should take a look at the [`reqwest`](https://docs.rs/reqwest/latest/reqwest/) crate, which implements the same HTTP request API for both platforms.

**Comment by janschiefer** [comment]
Nice!

There should be an example using this method.
