### ISSUE TITLE
leptos/leptos_macro/src/props.rs should support #[prop(optional, default=true)]

### ISSUE THREAD

**Issue by Rick9622092** [gbj/leptos#271]
leptos/leptos_macro/src/props.rs should support

-  #[prop(optional, default=true)]
- #[prop(optional, default=3500)]

**Comment by DPM97** [comment]
I can work on this

**Comment by gbj** [comment]
@DPM97 Thanks, sounds good. We use [TypedBuilder](https://docs.rs/typed-builder/latest/typed_builder/derive.TypedBuilder.html) under the hood, which does have `default=...`, so it should be a simple matter of passing that value through to them.

**Comment by DPM97** [comment]
shouldn't default imply optional? here ya go --> #279

**Comment by gbj** [comment]
Thanks—this is merged.
