### ISSUE TITLE
Add `Resource::cancel` so we can abort running futures if we want

### ISSUE THREAD

**Issue by gbj** [gbj/leptos#32]
There's an [`on_cleanup`](https://docs.rs/leptos/0.0.10/leptos/fn.on_cleanup.html) function that can be used to run arbitrary code before a scope is disposed, e.g., before a row is dropped in a `<For/>` component or before a nested route is disposed in the router (because you're navigating away from it).

It would be awesome to have a `Resource::cancel()` available so you can do things like abort in-flight `fetch` requests, etc. 

I've seen plenty of `Future`s that have some kind of cancel/abort feature. For example, the `oneshot` channel in the `futures` crate returns [`Result<Option<T>, Canceled>`](https://docs.rs/futures/latest/futures/channel/oneshot/struct.Receiver.html#method.try_recv). 

**Does anyone know there's a common way to indicate a cancellable future?** I'm imagining, for example, a `Cancellable` trait so that we have something like

```rust
pub fn create_cancellable_resource<S, T, Fu>(
    cx: Scope,
    source: impl Fn() -> S + 'static,
    fetcher: impl Fn(S) -> Fu + 'static,
) -> Resource<S, T>
where
    S: PartialEq + Debug + Clone + 'static,
    T: Debug + Clone + Serialize + DeserializeOwned + 'static,
    Fu: ***Cancellable*** + Future<Output = T> + 'static,
{
}
```

I'm realizing as I write this that, because the `Resource` struct isn't generic over the type of its `Future` at the moment (only `create_resource` is, then it stores it as a `Pin<Box<dyn Future ...>>` or somesuch) this is a little cumbersome.

I guess I could just define my own `Cancellable` trait for people to implement, but I'd love to have something from the wider Rust ecosystem if it exists.

**Comment by gbj** [comment]
So I don't think there's actually a very generic way to do this, but if an async action *can* be canceled, you can use `on_cleanup` to do it. I've added an example of that to the Hackernews example.

**Comment by M1cha** [comment]
As far as I understand all futures are cancellable by simply dropping them. It may have unexpected side-effects depending on the implementation of the future but that's up to the user to analyze.

**Comment by emirror-de** [comment]
Hey,
is there also a possibility to also cancel an `Action`?

For example if there is a long running task like a conversion of audio or images running as `Action` and the user wishes to cancel that.
```rust
fn Component() -> impl IntoView {
    let action = create_action(move |_| {
        async move {
          long_running_async_function.await
       }
    });
    let stop_action = move |_| {
        // how do I stop the action?
    };
    view! {
        <button on:click=move |_| action.dispatch(())>Start</button>
        <button on:click=stop_action>Stop</button>
    }
}
```

 Is there a recommended way to do this?
