### ISSUE TITLE
Bug: Leptos_DOM Child.rs IntoChild Trait Build Error

### ISSUE THREAD

**Issue by tcardlab** [gbj/leptos#39]
Tried to simply build everything with `cargo build` from root directory:
<img width="982" alt="Screen Shot 2022-10-28 at 11 59 03 AM" src="https://user-images.githubusercontent.com/35203441/198685252-efd16c4d-d334-45ca-a627-01dcaec535d6.png">

It builds by itself:
```
cd leptos_dom
cargo build
```

Seems to be the *hackernews* and *todomvc-ssr* examples.
Edit: ^ nvm, i just wasn't building *hackernews* and *todomvc-ssr* subdirectories individually

**Comment by ArthurianX** [comment]
I'm about to try this as well, and was looking at issues.
You can close this then @tcardlab.

**Comment by gbj** [comment]
Leave it open for a bit and I'll close it -- this is an actual issue with mismatched feature flags and very simple to fix, I just haven't had time. It won't cause issues when building actual apps or examples but is annoying in rust-analyzer

**Comment by gbj** [comment]
Okay I'm going to close it now: `cargo check` on the main `leptos` directory should fail but now gives a hopefully more useful compile error about feature flags.
