### ISSUE TITLE
Components are rendering out of order when mixed with HTML elements

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#53]
Using version `0.0.15`, the following results in out of order rending:

```rust
use leptos::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() {
  mount_to_body(view_fn);
}

fn view_fn(cx: Scope) -> impl Mountable {
  view! { cx,
    <form>
      <TextInput />
      <button>"Clcik me?"</button>
    </form>
  }
}

#[component]
fn TextInput(cx: Scope) -> Element {
  view! {cx,
    <input />
  }
}
```

If I inline the component, i.e, `<form><input /> ...`, then it works, if I remove the surrounding `<form>` then it also renders correctly.

**Comment by gbj** [comment]
Thanks, I'll take a look.

For you or anyone else who wants an ugly quick fix in the interim, wrapping the component in a <div> should almost certainly put them in the right order.

**Comment by jquesada2016** [comment]
Can confirm wrapping components in (what I presume to be `<span>` does work, at least with all the different experiments I've tried.

I'm working on a relatively large project and will report on any other odd behaviors I may find. I'll also try to read up on the source so I can make pull requests so you're not doing everything by yourself.

If you believe you can get a chance on perhaps making a quick doc somewhere describing how the internals work, that would go a huge way for me and other contributers to be able to help. I can also open an issue on this topic, or document everything I find while going through the source.
