### ISSUE TITLE
Is it possible to condense the three-directory server/client/app model into one?

### ISSUE THREAD

**Issue by gbj** [gbj/leptos#68]
We've been talking on Discord a little about this.

I think it should be possible, now that the `csr`/`ssr`/`hydrate` features aren't mutually exclusive, to write a complete server-rendered-and-browser-hydrated app in a single directory.

Browser/specific code can compile on the server, but not run. Server code usually can't compile for Wasm.

You'd need to use `#[wasm_bindgen]` to annotate the function you are using to hydrate the app (i.e., basically the few lines of code that are in `hackernews-client`), and call that function from the HTML you're generating on the server.

Then put the actual server code behind a `#[cfg(feature = "ssr")]` flag so that it doesn't try to compile `actix-web` or whatever to Wasm.

Bonus points if it's also Trunk-compatible for an easy dev-mode client-side-rendered version.

If someone wants to try it out in the `hackernews` directory and submit a PR I'd give them major kudos. @akesson it seems like this may be up your alley as you're working on `cargo-leptos` too... Let me know if you're interested in giving it a try.

**Comment by akesson** [comment]
I'll add it to my `cargo-leptos` todo list.

**Comment by gbj** [comment]
Answer: [yes](https://github.com/gbj/leptos-sfa).

**Comment by gbj** [comment]
Answer: [yes](https://github.com/gbj/leptos-sfa).
