### ISSUE TITLE
Having exactly two children produces type error

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#79]
The following fails to compile:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() {
  console_error_panic_hook::set_once();

  mount_to_body(view_fn);
}

fn view_fn(cx: Scope) -> impl Mountable {
  view! { cx,
    <span>
      {"1"}
      {"2"}
    </span>
  }
}
```

But the following does:

```rust
  view! { cx,
    <span>
      {"1"}
      {"2"}    // <-- only having exactly 2 children produces the error
      {"3"}
    </span>
  }
```

**Comment by gbj** [comment]
Thanks, I've noticed some new rendering bugs between siblings like this and am working on a more systematic solution for a wide variety of combinations

https://github.com/gbj/leptos/pull/78/commits/780c6d2e64a11fb0161f946f18bdd478fcb6edac#diff-03cbb1784908cc2a09e8a3cb52fb54bc523c3512d547e7c0b70f1541ef6eaf73

**Comment by gbj** [comment]
Okay this should be fixed now.
