### ISSUE TITLE
Consider adding `ReadSignal::derive` method

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#84]
I know derived signals are simply `impl Fn()` which calls a signal within itself, however, it would be very convenient to be able to call a derive method on the signal to get back a concrete type of `Signal<_>`, otherwise monomorphization can take a considerable size toll on methods which take `impl Fn() -> + 'static`, or a performance hit when using `Box<dyn Fn() -> _>`. It would be much simpler to be able to take a concrete type of `Signal<_>`, but there is currently no way to achieve this.

**Comment by gbj** [comment]
I think this is a great idea. I'm imagining something like

```rust
struct Signal<T>(Box<dyn Fn() -> T>);
```

so that `ReadSignal`, `RwSignal`, `Memo`, and `Signal::derive()` can all produce it. Having a single concrete type like this is probably a great idea.

(I *do* think it needs be be boxed like that, otherwise it's just as many generics because `Signal` would need to be generic over the function)

Thoughts?

**Comment by jquesada2016** [comment]
That does make sense, it would also still give users the ability to choose to use generics if they prefer the slight performance gains (besides the single dynamic dispatch).

Another possibility would be to perhaps choose one or the other? Something like

```rust
struct Signal<T, F = fn() -> T>(SignalKind);

enum SignalKind<T, F = fn() -> T>{
  Dyn(Box<dyn Fn() -> T>),
  Generic(F),
}
```

I'm not sure how this would affect other API's though because I know sometimes default type perameters don't work as expected...

**Comment by gbj** [comment]
You know what there's an even better way, I think

```rust
pub enum Signal<T> {
  ReadSignal(ReadSignal<T>),
  Memo(Memo<T>),
  Derived(Box<dyn Fn() -> T>)
}
```

This means it's zero-overhead for plain signals and memos.

I'll work on this later.

**Comment by gbj** [comment]
Done in #88
