### ISSUE TITLE
Consider adding the ability to get/set a signal's value without being tracked

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#85]
It can be somewhat easy to end up in an infinite reactivity loop when accessing/setting signals. Often times, it is desirable to access/set a value silently, without triggering that signal's dependents. This should be possible on all signal types, such as `ReadSignal`, `Memo`, etc. If [`ReadSignal::derive` mentioned here](#84) were to be implemented, it would make this even more useful, as I could imagine it not being possible to silently get a value if using just a plain `impl Fn() -> _`.

**Comment by gbj** [comment]
I think this is a great idea and the inner workings are already there

https://github.com/gbj/leptos/blob/96238c553e414664e0a688cf6e5804af4fc9dfe8/leptos_reactive/src/signal.rs#L149-L151

Would you like to offer a PR that implements something like `with_untracked` on `ReadSignal`/`RwSignal`/`Memo` and `set_untracked` on `WriteSignal`/`RwSignal`?

**Comment by jquesada2016** [comment]
Sure! How about an `UntrackedSignal` trait?

**Comment by gbj** [comment]
As opposed to similar associated functions? I think that probably makes sense.
