### ISSUE TITLE
Consider adding `MappedWriteSignal` as a complement to `Signal` and `MaybeSignal`

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#91]
Creating a type which maps it's input into an underlying Write/Rw signal would complete the elimination of needing generics in components to work with setter/getter signals.

The only thing to consider would be that `UntrackedSettableSignal` would need special consideration, as per [this comment](https://github.com/gbj/leptos/pull/89#issuecomment-1320078314).

**Comment by jquesada2016** [comment]
Currently, I believe there are only 3 distinct types:
- WriteSignal
- RwSignal
- impl Fn(T)

So the API should support something to the following effect:
```rust
let mapped_set_signal = move |v: _| set_signal(v);

/* make mapped_set_signal a concrete type */
```

I really think we should add core signal traits so a user can decide whether they want to take a concrete signal type, such as `Signal`, `ReadSignal`, or a generic, such as `T: GettableSignal`, but perhaps this belongs in a seperate issue.

**Comment by gbj** [comment]
Hm... I've honestly never thought of a "derived write signal" before. Would this be, for example, a closure that wraps a setter? (I guess this is where the name `MappedWriteSignal` you suggest comes from)

This does limit it to the `set` function of a writable signal rather than the `update` function.

**Comment by jquesada2016** [comment]
Yes, it would limit it to just setting the value. You could technically make it work for `update` with another type, but it would need to be an associated `fn` on the `Write` signal types.

**Comment by gbj** [comment]
Added in 41c03852e19f4896684f10e1680a90586bf4844a
