### ISSUE TITLE
Fine-grained reactivity: how does this compare with solidJS?

### ISSUE THREAD

**Issue by debpalash** [gbj/leptos#94]
on leptos:
` let (value, set_value) = create_signal(cx, initial_value);`

This looks quite similar with solidJS's.
`const [getter, Setter] = CreateSignal(value)` 

How's leptos and solidJS are similar on reactivity and primitives and What are your plans with leptos? 

Folks who wants to get their hands dirty with rust, leptos might be a good testing point as web dev, so i guess you maybe this answer the community questions.

**Comment by gbj** [comment]
You're right! Leptos uses an extremely similar model to Solid, based on building up your UI by composing fine grained reactive primitives. You'll notice most of the same basic patterns: signals, derived signals, memos, effects, resources, etc., as well as a very similar nested router. 

I think Solid is really well designed, and Leptos gets the closest to Solid's performance among the Rust/Wasm frameworks. 

Happy to discuss more on our Discord!
