### ISSUE TITLE
Fetch demo: cats count input `on:input` callback is not working 

### ISSUE THREAD

**Issue by alordash** [gbj/leptos#96]
I used code from [fetch example](https://github.com/gbj/leptos/tree/8077ae9eadb9a843c365de4137b9ae3d59e321d6/examples/fetch).
When running this example locally, nothing changes when I change number of cats.
However, if I add `on:input` callback to input's label, then it works:
```rs
<label on:input=move |ev| {
    let val = event_target_value(&ev).parse::<u32>().unwrap_or(0);
    set_cat_count(val);
}>
    "How many cats would you like?"
    <input type="number"
        value={move || cat_count.get().to_string()}
    />
</label>
```
Removing label also fixes callback not firing.

**Comment by gbj** [comment]
Hm... I'm not able to reproduce this. 

1) I'm going to guess that wrapping "How many cats" in a `<span>` also fixes it? Is that correct?
2) Are you running this within the repository, or as a separate example and if so, using what Leptos version? (If you're running locally using `leptos = "0.0"` is it `0.0.16` or `0.0.17`? Is it fixed if you update to `0.0.17` or use a git dependency on the repo, i.e., `leptos = { git = "https://github.com/gbj/leptos" }` in your `Cargo.toml`)

**Comment by alordash** [comment]
I was running it using `leptos = "0.0.16"`. Switching to `0.0.17` actually fixed the issue!

**Comment by gbj** [comment]
Perfect! Yeah 0.0.16 had a rendering bug unfortunately.
