### ISSUE TITLE
Router duplicate rendered paths

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#97]
Take the following example:

```rust
use leptos::*;
use leptos_router::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() {
  console_error_panic_hook::set_once();

  mount_to_body(view_fn);
}

fn view_fn(cx: Scope) -> impl Mountable {
  provide_context(cx, RouterIntegrationContext::new(BrowserIntegration {}));

  view! { cx,
    <span>
      <Router>
        <main>
          <A href="/a">"Go to path A"</A>
          <Routes>
            <Route path="/" element=|cx| view! { cx, <h1>"Home"</h1> } />
            <Route path="/a" element=path_a />
          </Routes>
        </main>
      </Router>
    </span>
  }
}

fn path_a(cx: Scope) -> Vec<Element> {
  view! { cx,
    <>
      <h1>"Path A"</h1>
      <A href="/">"Go back"</A>
    </>
  }
}
```

If you press "Go to path A" and then "Go back", for each time you click "Go back", it's douplicate that path,.

**Comment by gbj** [comment]
This was a smallish issue in the renderer having to do with swapping between a fragment and an element.

I really appreciate all the bugs you've found — such a great help. 

I don't know if you use Discord but there are a number of people who are active on the Leptos Discord (link in the top of the Readme) if you ever want to join in discussion there as well.

**Comment by jquesada2016** [comment]
> I really appreciate all the bugs you've found — such a great help.

Of course! Sorry for not being able to make that many PR's, I'll definitely have more time for this in about a week or so.

>  don't know if you use Discord but there are a number of people who are active on the Leptos Discord (link in the top of the Readme) if you ever want to join in discussion there as well.

Thanks! I did not know, I'll definitely join later today!
